language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev
    - mkdir -p build/logs

after_script:
    - php vendor/bin/coveralls -v
